version: 2

updates:

  - package-ecosystem: "pip"
    directory: "/data"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
